# Generated by Django 5.2.4 on 2025-10-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='identity_groups',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='identity_organizations',
        ),
        migrations.AlterModelTable(
            name='user',
            table='identity_users',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='identity_usergroups',
        ),
    ]
