# Generated by Django 5.2.4 on 2025-10-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organizationid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='identity.organization'),
        ),
    ]
