# Generated by Django 5.2.4 on 2025-10-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_usergroup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('office', 'Office'), ('host', 'Host'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
    ]
