# Generated by Django 5.2.4 on 2025-10-24 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_add_userrecruitment'),
        ('scheduling', '0006_merge_20251024_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(db_column='subjectid', on_delete=django.db.models.deletion.CASCADE, related_name='subject_users', to='scheduling.subject')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_usersubjects',
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
