services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - USE_REDIS=True
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  progress-listener:
    build: .
    environment:
      - USE_REDIS=True
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    command: python manage.py listen_progress
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started