services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --timeout 0

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DB_DIR=/app/data
    depends_on:
      - redis
    volumes:
      - db_data:/app/data

  progress-listener:
    build: ./backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DB_DIR=/app/data
    command: ["python", "manage.py", "listen_progress"]
    depends_on:
      - redis
    volumes:
      - db_data:/app/data
    restart: unless-stopped

volumes:
  db_data: