# Generated by Django 5.2.4 on 2025-10-21 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('max_execution_time', models.IntegerField(help_text='Maximum execution time in seconds')),
                ('problem_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('final_solution', models.JSONField(blank=True, null=True)),
                ('current_iteration', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iteration', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('best_solution', models.JSONField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='optimizer.optimizationjob')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('job', 'iteration')},
            },
        ),
    ]
