# Generated by Django 5.2.4 on 2025-09-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptimizationConfig',
        ),
        migrations.RenameField(
            model_name='optimizationjob',
            old_name='final_result',
            new_name='final_solution',
        ),
        migrations.RemoveField(
            model_name='optimizationjob',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='optimizationjob',
            name='total_iterations',
        ),
        migrations.RemoveField(
            model_name='optimizationprogress',
            name='algorithm_metadata',
        ),
        migrations.RemoveField(
            model_name='optimizationprogress',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='optimizationprogress',
            name='convergence_rate',
        ),
        migrations.RemoveField(
            model_name='optimizationprogress',
            name='generations_without_improvement',
        ),
        migrations.RemoveField(
            model_name='optimizationprogress',
            name='population_diversity',
        ),
    ]
