# Generated by Django 5.2.4 on 2025-10-05 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_delete_optimizationconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationprogress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
