# Generated by Django 5.2.4 on 2025-10-21 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recruitment_name', models.CharField(max_length=255)),
                ('day_start_time', models.TimeField(blank=True, null=True)),
                ('day_end_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cycle_type', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], db_column='cycletype', default='weekly', max_length=20)),
                ('plan_status', models.CharField(choices=[('archived', 'Archived'), ('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20)),
                ('default_token_count', models.IntegerField(default=40)),
                ('round_count', models.IntegerField(default=1)),
                ('round_break_length', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'scheduling_recruitments',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'scheduling_rooms',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'scheduling_subjects',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'scheduling_tags',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_hour', models.IntegerField(help_text='Start hour (0-23)')),
                ('end_hour', models.IntegerField(help_text='End hour (0-23)')),
                ('day_of_week', models.IntegerField(help_text='Day of week (0=Monday, 6=Sunday)')),
                ('day_of_cycle', models.IntegerField(help_text='Day in cycle: weekly 0-6, biweekly 0-13, monthly 0-30')),
                ('group', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='identity.group')),
                ('host_user', models.ForeignKey(db_column='teacherid', on_delete=django.db.models.deletion.CASCADE, related_name='taught_meetings', to=settings.AUTH_USER_MODEL)),
                ('recruitment', models.ForeignKey(db_column='recruitmentid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.recruitment')),
                ('room', models.ForeignKey(db_column='roomid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.room')),
                ('subject', models.ForeignKey(db_column='subjectid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.subject')),
                ('required_tag', models.ForeignKey(blank=True, db_column='requiredtagid', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.tag')),
            ],
            options={
                'db_table': 'scheduling_meetings',
            },
        ),
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.ForeignKey(db_column='roomid', on_delete=django.db.models.deletion.CASCADE, related_name='room_tags', to='scheduling.room')),
                ('tag', models.ForeignKey(db_column='tagid', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_rooms', to='scheduling.tag')),
            ],
            options={
                'db_table': 'scheduling_roomtags',
                'unique_together': {('room', 'tag')},
            },
        ),
    ]
