# Generated by Django 5.2.4 on 2025-10-05 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_alter_group_table_alter_organization_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitment_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('winter', 'Winter'), ('summer', 'Summer')], max_length=20)),
            ],
            options={
                'db_table': 'scheduling_recruitments',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'scheduling_rooms',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'scheduling_subjects',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'scheduling_tags',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('recruitment', models.ForeignKey(db_column='recruitmentid', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='scheduling.recruitment')),
            ],
            options={
                'db_table': 'scheduling_plans',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_hour', models.IntegerField(help_text='Start hour (0-23)')),
                ('end_hour', models.IntegerField(help_text='End hour (0-23)')),
                ('day_of_week', models.IntegerField(help_text='Day of week (0=Monday, 6=Sunday)')),
                ('day_of_cycle', models.IntegerField(help_text='Day in cycle: weekly 0-6, biweekly 0-13, monthly 0-30')),
                ('cycle_type', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('group', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='identity.group')),
                ('teacher', models.ForeignKey(db_column='teacherid', on_delete=django.db.models.deletion.CASCADE, related_name='taught_meetings', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(db_column='planid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.plan')),
                ('recruitment', models.ForeignKey(db_column='recruitmentid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.recruitment')),
                ('room', models.ForeignKey(db_column='roomid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.room')),
                ('subject', models.ForeignKey(db_column='subjectid', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.subject')),
            ],
            options={
                'db_table': 'scheduling_meetings',
            },
        ),
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(db_column='roomid', on_delete=django.db.models.deletion.CASCADE, related_name='room_tags', to='scheduling.room')),
                ('tag', models.ForeignKey(db_column='tagid', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_rooms', to='scheduling.tag')),
            ],
            options={
                'db_table': 'scheduling_roomtags',
                'unique_together': {('room', 'tag')},
            },
        ),
    ]
