# Generated by Django 5.2.4 on 2025-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='end_date',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='recruitment',
            old_name='start_date',
            new_name='host_prefs_start_date',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='optimization_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='optimization_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='preference_threshold',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='user_prefs_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='users_submitted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='default_token_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='plan_status',
            field=models.CharField(choices=[('archived', 'Archived'), ('draft', 'Draft'), ('optimizing', 'Optimizing'), ('active', 'Active')], default='draft', max_length=20),
        ),
    ]
