# Generated by Django 5.2.4 on 2025-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_rename_end_date_recruitment_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='round_break_length',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='round_count',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='max_round_execution_time',
            field=models.IntegerField(default=300),
        ),
    ]
