# Generated by Django 5.2.4 on 2025-10-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_meeting_meeting_id_alter_plan_plan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='teacher',
            new_name='host_user',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='cycle_type',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='year',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='cycle_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], db_column='cycletype', default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('optimized', 'Optimized'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
