# Generated by Django 5.2.4 on 2025-10-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_add_subjectgroup_and_update_subject_meeting'),
        ('scheduling', '0003_remove_recruitment_round_break_length_and_more'),
    ]

    operations = [
    ]
