# Generated by Django 5.2.4 on 2025-10-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_rename_teacher_meeting_host_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='plan',
        ),
        migrations.RenameField(
            model_name='recruitment',
            old_name='end_time',
            new_name='day_end_time',
        ),
        migrations.RenameField(
            model_name='recruitment',
            old_name='start_time',
            new_name='day_start_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='required_tag',
            field=models.ForeignKey(blank=True, db_column='requiredtagid', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.tag'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='default_token_count',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='plan_status',
            field=models.CharField(choices=[('archived', 'Archived'), ('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='round_break_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='round_count',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
