# Generated by Django 5.2.4 on 2025-10-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_merge_20251024_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='duration_blocks',
            field=models.IntegerField(default=4, help_text='duration in 15-minute blocks (4 = 1 hour)'),
        ),
    ]
