# Generated by Django 5.2.4 on 2025-10-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_subject_duration_blocks'),
        ('scheduling', '0005_move_host_user_to_subjectgroup'),
    ]

    operations = [
    ]
