# Generated by Django 5.2.4 on 2025-10-21 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('constraints_data', models.JSONField(default=dict)),
                ('recruitment', models.OneToOneField(db_column='recruitmentid', on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduling.recruitment')),
            ],
            options={
                'db_table': 'preferences_constraints',
            },
        ),
        migrations.CreateModel(
            name='ManagementPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferences_data', models.JSONField(default=dict)),
                ('recruitment', models.OneToOneField(db_column='recruitmentid', on_delete=django.db.models.deletion.CASCADE, related_name='management_preferences', to='scheduling.recruitment')),
            ],
            options={
                'db_table': 'preferences_management_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferences_data', models.JSONField(default=dict)),
                ('recruitment', models.ForeignKey(db_column='recruitmentid', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='scheduling.recruitment')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preferences_user_preferences',
                'unique_together': {('user', 'recruitment')},
            },
        ),
    ]
